#!/usr/bin/env ansible-playbook
# File: setup_aap_project.yml
# GitHub: https://github.com/makeitworkcloud/aap-libvirt-infra
# Description: This playbook creates the libvirt-infra project in Ansible Automation Platform (AAP).
# Author:
#                                   _|
#   _|    _|  _|_|_|      _|_|    _|_|_|_|    _|_|
#     _|_|    _|    _|  _|    _|    _|      _|    _|
#   _|    _|  _|    _|  _|    _|    _|      _|    _|
#   _|    _|  _|    _|    _|_|        _|_|    _|_|
---
- name: Load SOPS values
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load vars task
      community.sops.load_vars:
        file: secrets/secrets.yaml

- name: Create project via API
  hosts: localhost
  tasks:
    - name: Create libvirt project
      ansible.builtin.uri:
        url: "https://{{ hostvars['localhost']['controller_host'] }}/api/controller/v2/projects/"
        method: POST
        user: "{{ hostvars['localhost']['controller_username'] }}"
        password: "{{ hostvars['localhost']['controller_password'] }}"
        force_basic_auth: true
        body_format: json
        body:
          name: "libvirt-infra"
          description: "Created via URI module"
          scm_type: "git"
          scm_url: "https://github.com/makeitworkcloud/aap-libvirt-infra.git"
          organization: 1
        status_code: 201
        validate_certs: true
      register: result

    - name: Show result
      ansible.builtin.debug:
        var: result
...
