#!/usr/bin/env ansible-playbook
# File: configure_runner.yml
# GitHub: https://github.com/makeitworkcloud/aap-libvirt-infra/playbooks/configure_runner.yml
# Description: This playbook configures a pre-provisioned GitHub Actions runner.
# Author:
#                                   _|
#   _|    _|  _|_|_|      _|_|    _|_|_|_|    _|_|
#     _|_|    _|    _|  _|    _|    _|      _|    _|
#   _|    _|  _|    _|  _|    _|    _|      _|    _|
#   _|    _|  _|    _|    _|_|        _|_|    _|_|
---
- name: Configure a pre-provisioned GitHub Actions runner
  hosts: runner
  gather_facts: false
  vars_files:
    - ../vars/configure_runner.yml
  tasks:
    - name: Add known hosts
      ansible.builtin.known_hosts:
        name: hostvars['localhost']['libvirt_host']
        key: "{{ lookup('pipe', 'ssh-keyscan ' ~ hostvars['localhost']['libvirt_fqdn']) }}"

    - name: Get latest GitHub Actions runner version
      ansible.builtin.uri:
        url: https://api.github.com/repos/actions/runner/releases/latest
        return_content: true
      register: actions_runner_json_reponse

    - name: Wait for port 22 to be open
      ansible.builtin.wait_for:
        host: "{{ runner_ipv4_addr }}"
        port: 22
        timeout: 300
        state: started

    - name: Install docker
      ansible.builtin.dnf:
        name: docker
        state: present

    - name: Start and enable docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
      become: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ runner_ssh_user }}"
        groups: docker
        append: true
      become: true

    - name: Download GitHub Actions runner
      ansible.builtin.get_url:
        url: >-
          {{ 'https://github.com/actions/runner/releases/download/' ~ actions_runner_json_reponse.json.tag_name
          ~ '/actions-runner-linux-x64-' ~ actions_runner_json_reponse.json.tag_name ~ '.tar.gz' }}
        dest: "/tmp/actions-runner-linux-x64-{{ actions_runner_json_reponse.json.tag_name }}.tar.gz"
        owner: "{{ runner_ssh_user }}"
        mode: '0644'

    - name: Extract GitHub Actions runner
      ansible.builtin.unarchive:
        src: "/tmp/actions-runner-linux-x64-{{ actions_runner_json_reponse.json.tag_name }}.tar.gz"
        dest: "/home/{{ runner_ssh_user }}/actions-runner"
        remote_src: true
        owner: "{{ runner_ssh_user }}"
        group: "{{ runner_ssh_user }}"

    - name: Configure GitHub Actions runner
      ansible.builtin.shell:
        cmd: |
          ./config.sh --name libvirt-infra --labels libvirt --url https://github.com/makeitworkcloud --token {{ runner_github_token }}
          sudo ./svc.sh install
        args:
          chdir: "/home/{{ runner_ssh_user }}/actions-runner"
      changed_when: true
