#!/usr/bin/env ansible-playbook
# File: configure_torwww.yml
# GitHub: https://github.com/makeitworkcloud/aap-libvirt-infra/playbooks/configure_torwww.yml
# Description: This playbook configures a pre-provisioned Onion web mirror.
# Author:
#                                   _|
#   _|    _|  _|_|_|      _|_|    _|_|_|_|    _|_|
#     _|_|    _|    _|  _|    _|    _|      _|    _|
#   _|    _|  _|    _|  _|    _|    _|      _|    _|
#   _|    _|  _|    _|    _|_|        _|_|    _|_|
---
- name: Configure a pre-provisioned Onion web mirror
  hosts: torwww
  gather_facts: false
  vars_files:
    - ../vars/configure_torwww.yml
  tasks:
    - name: Wait for port 22 to be open on the node
      ansible.builtin.wait_for:
        host: "{{ torwww_ipv4_addr }}"
        port: 22
        timeout: 300
        state: started
      delegate_to: "{{ libvirt_host }}"

    - name: Propagate /var/www
      ansible.builtin.file:
        path: /var/www
        state: directory
        owner: nginx
        group: nginx
        mode: "0755"
      become: true

    - name: Propagate /var/www/html
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: nginx
        group: nginx
        mode: "0755"
      become: true

    - name: Change server in /etc/nginx/nginx.conf
      ansible.builtin.lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: "^        listen       80;$"
        line: "        listen       127.0.0.1:80;"
      become: true

    - name: Remove IPV6 in /etc/nginx/nginx.conf
      ansible.builtin.lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: "^        listen       [::]:80;"
        state: absent
      become: true

    - name: Change web dir in /etc/nginx/nginx.conf
      ansible.builtin.lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: "^        root         /usr/share/nginx/html;"
        line: "        root         /var/www/html;"
      become: true

    - name: Copy git config file
      ansible.builtin.copy:
        content: |
          location ~ /\. {
            deny all;
          }
        dest: /etc/nginx/default.d/git.conf
        owner: nginx
        group: nginx
        mode: "0644"
      become: true

    - name: Clone git repo
      ansible.builtin.git:
        repo: https://github.com/makeitworkcloud/www.git
        dest: /var/www/html
        version: main
      become: true
      become_user: nginx

    - name: Cronjob to sync repo every half hour
      ansible.builtin.cron:
        name: "git-clone"
        minute: "*/15"
        user: nginx
        job: "cd /var/www/html && git pull"
      become: true

    - name: Start & Enable nginx
      ansible.builtin.systemd:
        name: nginx.service
        state: started
        enabled: true
      become: true

    - name: Start & Enable warp-svc service
      ansible.builtin.systemd:
        name: warp-svc.service
        enabled: true
        state: started
      become: true

    - name: Start & Enable WARP
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          yes | warp-cli registration new -- --accept-tos
          yes | warp-cli connect
      changed_when: false
      become: true
      become_user: "{{ torwww_username }}"

    - name: Verify WARP is on
      ansible.builtin.uri:
        url: "https://cloudflare.com/cdn-cgi/trace"
        return_content: true
      register: cloudflare_trace
      until: "'warp=on' in cloudflare_trace.content"
      retries: 10
      delay: 1

    - name: Enable ControlPort
      ansible.builtin.lineinfile:
        path: "/etc/tor/torrc"
        regexp: "^#ControlPort 9051$"
        line: "ControlPort 9051"
      become: true

    - name: Enable HiddenServiceDir
      ansible.builtin.lineinfile:
        path: "/etc/tor/torrc"
        line: "HiddenServiceDir /var/lib/tor/hidden_service/"
        state: present
        insertafter: "^############### This section is just for location-hidden services ###$"
      become: true

    - name: Define HiddenServiceVersion
      ansible.builtin.lineinfile:
        path: "/etc/tor/torrc"
        line: "HiddenServiceVersion 3"
        state: present
        insertafter: "^HiddenServiceDir /var/lib/tor/hidden_service/$"
      become: true

    - name: Enable Web HiddenServicePort
      ansible.builtin.lineinfile:
        path: "/etc/tor/torrc"
        line: "HiddenServicePort 80 127.0.0.1:80"
        state: present
        insertafter: "^HiddenServiceVersion 3$"
      become: true

    - name: "Start & Disable Tor"
      ansible.builtin.systemd:
        name: tor.service
        state: started
        enabled: false
      become: true
