name: Check AAP Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Deploy AAP Content
        run: |
          ansible-playbook setup_aap_project.yml --check --diff
