name: Deploy AAP Content

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
  ANSIBLE_VAULT_PASSWORD_FILE: ./scripts/vault.bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install ansible pre-commit

      - name: pre-commit tests
        uses: pre-commit/action@v3.0.1

      - name: Deploy AAP Content
        run: |
          ansible-playbook cd/setup_aap_project.yml
